# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c67f6d9ad09a033fb13c6e68ccd2fa9a3b0c4a5e0d8d9986b057cea09ecd603d94674396c4aa4c458defdbe03bcef1308808bb66bf451e06e43c9d0f8b67aefb

test:
  secret_key_base: 27b97b5683fc0660379ad0fa44b297bfb13b4c50968f1df918eabe07aeb0af9badcca75e8127eecca5a0b16520c8ae4fe0f30124a26d4a74caa8b3aef68ac6ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
